/*
 * hduc_ctl - experimental USB control tool for the SKNET HDUC (ASIE5607)
 *
 * Implements, in Linux/libusb form, the AS11Loader-compatible firmware
 * upload container protocol reverse engineered from the official
 * SKNET_AS11Loader.sys (Ver.1.9.10.20, 2009-11-10) and cross-checked
 * against the ASIE5606-era recfriio/as11loader.c implementation.
 * See README.md in the project root for usage and safety notes.
 *
 * This tool does NOT embed any vendor firmware or cryptographic key
 * material. The --loader-upload command requires the caller to supply
 * an owner-supplied, already-decrypted firmware image.  No extraction key or
 * vendor driver or DLL is distributed here; see NOTICE.md.
 */

#include <libusb-1.0/libusb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>
#include <signal.h>
#include <errno.h>
#include <poll.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <unistd.h>

#define LOADER_VID 0x1738
#define LOADER_PID 0x5211
#define HDTVC_VID 0x3275
#define HDTVC_PID 0x7080
#define LOADER_IDX_DEFAULT 0x55d8 /* wValue used by the 2009 HDUC-era AS11Loader */
#define CTRL_TIMEOUT_MS 5000
#define BULK_TIMEOUT_MS 3000
#define ASYNC_MAX_BUFFERS 32
#define ASYNC_MAX_TRANSFER 65536

/* Optional physical USB location filter.  This matters when an HDUC and a
 * U3 are both present in loader mode: both expose the same 1738:5211 ID. */
static int selected_bus = -1;
static int selected_port = -1;

struct fw_chunk {
    uint8_t  bRequest;
    uint32_t offset;
    uint32_t size;
};

/* Sequence reverse engineered from SKNET_AS11Loader.sys FUN_0001078e.
 * Identical container shape to the ASIE5606-era recfriio as11loader.c. */
static const struct fw_chunk LOADER_SEQUENCE[] = {
    { 0xab, 0x0000, 0x0c00 },
    { 0xab, 0x2000, 0x0400 },
    { 0xab, 0x2800, 0x1000 },
    { 0xac, 0x3800, 0x0800 },
};

static void print_usage(const char *prog)
{
    fprintf(stderr,
        "hduc_ctl - HDUC/ASIE5607 experimental USB control tool\n\n"
        "Usage:\n"
        "  %s info [--vid VID --pid PID] [--bus N --port N]\n"
        "      Open the device and print descriptors (default VID:PID = loader mode 1738:5211).\n\n"
        "  %s loader-upload <firmware.bin> [--idx WVALUE] [--bus N --port N]\n"
        "      Replay the AS11Loader-compatible firmware upload sequence against a\n"
        "      device in loader mode (1738:5211). firmware.bin must already be the\n"
        "      *decrypted* plaintext firmware payload (>= 0x4000 bytes). This tool\n"
        "      performs no decryption; see the project README and NOTICE.\n\n"
        "  %s vendor-ctl --vid VID --pid PID --dir in|out --req REQ --val VAL --idx IDX --len LEN [--data HEXBYTES]\n"
        "      Send/receive one arbitrary USB vendor control transfer for protocol\n"
        "      experimentation (e.g. against the 3275:7080 post-load HDTV-C identity).\n\n"
        "  %s replay-control --vid VID --pid PID --file SEQUENCE [--dry-run] [--scale FACTOR] [--quiet]\n"
        "      [--proxy-retries N] [--keep-going]\n"
        "      [--ep 0x81 --seconds N --out FILE]  # after the sequence, stream Bulk IN on the SAME handle\n"
        "      Replay a recorded vendor-control sequence while keeping one USB handle open.\n"
        "      SEQUENCE is a text file (or '-' for stdin) generated by\n"
        "      scripts/extract_u3_replay.py.  This is intended only for a sequence\n"
        "      captured from the same device model; --dry-run performs no USB I/O.\n"
        "      --proxy-retries repeats failed U3 0x25/0x26 transfers after 10 ms\n"
        "      without issuing CLEAR_FEATURE on endpoint zero.\n\n"
        "  %s async-bulk --vid VID --pid PID --ep 0x81|0x82 [--seconds N] [--buffers N] [--size N] [--out FILE]\n"
        "      [--start 0x06 --hduc-post-start] [--hold-after N --ready-file FILE]\n"
        "      Queue multiple asynchronous Bulk IN requests without sending any\n"
        "      control transfer.  Intended for the U3/HDTV-C data plane after a\n"
        "      correctly initialized driver has started streaming. Defaults: 8\n"
        "      buffers, 8192 bytes each, 5 seconds. --hold-after keeps the SAME\n"
        "      handle alive after capture (0=until signal); --ready-file is created\n"
        "      after the output has been flushed and the hold phase begins.\n"
        "      --seconds 0 receives until SIGINT/SIGTERM.\n\n"
        "  %s hduc-server --socket PATH --channel N [--bus N --port N]\n"
        "      Keep one initialized HDTV-C handle open and serve recpt1-hduc\n"
        "      clients over a Unix socket. Protocol: RECORD channel seconds\\n\n"
        "      seconds=0 streams until the client disconnects. One client at a time.\n\n"
        "  %s u3-monitor --vid 0x3275 --pid 0x9010 [--seconds N] [--interval-ms N]\n"
        "      Read-only monitor for the two U3 status probes observed in Windows\n"
        "      captures (0x02/0x8b30 and 0x02/0xc332). It reports the device\n"
        "      acknowledgement byte without sending a tuning command.\n\n"
        "  %s hduc-keepalive [--seconds N] [--interval-ms N] [--bus N --port N]\n"
        "      Keep an initialized HDTV-C runtime alive with the read-only Windows\n"
        "      heartbeat/status cadence. N=0 means until SIGINT/SIGTERM.\n\n"
        "  %s reset --vid VID --pid PID\n"
        "      Issue a USB port reset (libusb_reset_device) and re-print descriptors.\n\n"
        "  %s tune --channel N [--dry-run] [--bus N --port N]\n"
        "      Tune an already initialized HDTV-C runtime (3275:7080) to Japanese\n"
        "      terrestrial physical channel 13..62.  This sends the verified\n"
        "      0x02/0x03/0x0d/0x0e tuner sequence and does not start Bulk IN.\n\n"
        "  %s dump-bulk --ep 0x81|0x82 [--seconds N] [--out FILE]\n"
        "      Read raw bytes from a Bulk IN endpoint on the HDTV-C device for N seconds\n"
        "      (default 5) and report whether MPEG-TS sync bytes (0x47 every 188 bytes)\n"
        "      are present. Optionally save the raw stream to FILE.\n",
        prog, prog, prog, prog, prog, prog, prog, prog, prog, prog, prog);
}

static libusb_device_handle *open_dev(libusb_context *ctx, uint16_t vid, uint16_t pid)
{
    libusb_device_handle *h = NULL;
    libusb_device **list = NULL;
    ssize_t count = libusb_get_device_list(ctx, &list);
    if (count < 0) {
        fprintf(stderr, "error: could not enumerate USB devices: %s\n", libusb_error_name((int)count));
        return NULL;
    }

    for (ssize_t i = 0; i < count; i++) {
        struct libusb_device_descriptor desc;
        if (libusb_get_device_descriptor(list[i], &desc) != 0 ||
            desc.idVendor != vid || desc.idProduct != pid)
            continue;
        if (selected_bus >= 0 && libusb_get_bus_number(list[i]) != selected_bus)
            continue;
        if (selected_port >= 0) {
            uint8_t ports[8];
            int nports = libusb_get_port_numbers(list[i], ports, sizeof(ports));
            if (nports < 1 || ports[0] != selected_port)
                continue;
        }
        if (libusb_open(list[i], &h) == 0)
            break;
        h = NULL;
    }
    libusb_free_device_list(list, 1);
    if (!h) {
        if (selected_bus >= 0 || selected_port >= 0)
            fprintf(stderr, "error: could not open device %04x:%04x at USB bus %d port %d\n",
                    vid, pid, selected_bus, selected_port);
        else
            fprintf(stderr, "error: could not open device %04x:%04x (not found or permission denied)\n",
                    vid, pid);
        return NULL;
    }
    if (libusb_kernel_driver_active(h, 0) == 1) {
        libusb_detach_kernel_driver(h, 0);
    }
    int rc = libusb_claim_interface(h, 0);
    if (rc != 0) {
        fprintf(stderr, "warning: libusb_claim_interface failed: %s\n", libusb_error_name(rc));
    }
    return h;
}

static void print_descriptors(libusb_device_handle *h)
{
    libusb_device *dev = libusb_get_device(h);
    struct libusb_device_descriptor desc;
    libusb_get_device_descriptor(dev, &desc);

    printf("Device Descriptor:\n");
    printf("  idVendor          0x%04x\n", desc.idVendor);
    printf("  idProduct         0x%04x\n", desc.idProduct);
    printf("  bcdDevice         %x.%02x\n", desc.bcdDevice >> 8, desc.bcdDevice & 0xff);
    printf("  bNumConfigurations %d\n", desc.bNumConfigurations);

    unsigned char buf[256];
    int rc;
    rc = libusb_get_string_descriptor_ascii(h, desc.iManufacturer, buf, sizeof(buf));
    if (rc > 0) printf("  iManufacturer     \"%s\"\n", buf);
    rc = libusb_get_string_descriptor_ascii(h, desc.iProduct, buf, sizeof(buf));
    if (rc > 0) printf("  iProduct          \"%s\"\n", buf);

    struct libusb_config_descriptor *cfg;
    if (libusb_get_active_config_descriptor(dev, &cfg) == 0) {
        rc = libusb_get_string_descriptor_ascii(h, cfg->iConfiguration, buf, sizeof(buf));
        if (rc > 0) printf("  iConfiguration    \"%s\"\n", buf);
        for (int i = 0; i < cfg->bNumInterfaces; i++) {
            const struct libusb_interface_descriptor *ifd = &cfg->interface[i].altsetting[0];
            printf("  Interface %d: class=0x%02x subclass=0x%02x proto=0x%02x endpoints=%d\n",
                   ifd->bInterfaceNumber, ifd->bInterfaceClass, ifd->bInterfaceSubClass,
                   ifd->bInterfaceProtocol, ifd->bNumEndpoints);
            for (int e = 0; e < ifd->bNumEndpoints; e++) {
                const struct libusb_endpoint_descriptor *ep = &ifd->endpoint[e];
                printf("    EP 0x%02x  attr=0x%02x  wMaxPacketSize=%d\n",
                       ep->bEndpointAddress, ep->bmAttributes, ep->wMaxPacketSize);
            }
        }
        libusb_free_config_descriptor(cfg);
    }
}

static int cmd_info(libusb_context *ctx, uint16_t vid, uint16_t pid)
{
    libusb_device_handle *h = open_dev(ctx, vid, pid);
    if (!h) return 1;
    print_descriptors(h);
    libusb_release_interface(h, 0);
    libusb_close(h);
    return 0;
}

static int cmd_reset(libusb_context *ctx, uint16_t vid, uint16_t pid)
{
    libusb_device_handle *h = open_dev(ctx, vid, pid);
    if (!h) return 1;
    int rc = libusb_reset_device(h);
    printf("libusb_reset_device: %s\n", libusb_error_name(rc));
    print_descriptors(h);
    libusb_release_interface(h, 0);
    libusb_close(h);
    return 0;
}

static int send_fw_chunk(libusb_device_handle *h, const uint8_t *fw, size_t fw_len,
                          const struct fw_chunk *c, uint16_t idx)
{
    if (c->offset + c->size > fw_len) {
        fprintf(stderr, "error: firmware file too small for chunk at offset 0x%x size 0x%x\n",
                c->offset, c->size);
        return -1;
    }
    int rc = libusb_control_transfer(
        h,
        LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_OUT,
        c->bRequest,
        c->offset,         /* wValue: byte offset within firmware image (recfriio send_firm + official SKNET_AS11Loader.sys FUN_0001072e both put offset here) */
        idx,               /* wIndex: fixed idx (DAT_000155d0) */
        (unsigned char *)(fw + c->offset),
        c->size,
        CTRL_TIMEOUT_MS);
    printf("  bRequest=0x%02x wValue=0x%04x wIndex=0x%04x size=0x%04x -> %d %s\n",
           c->bRequest, c->offset, idx, c->size, rc,
           rc >= 0 ? "OK" : libusb_error_name(rc));
    return rc >= 0 ? 0 : -1;
}

static int cmd_loader_upload(libusb_context *ctx, const char *fwpath, uint16_t idx)
{
    FILE *f = fopen(fwpath, "rb");
    if (!f) { perror("fopen"); return 1; }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz <= 0) { fprintf(stderr, "error: empty firmware file\n"); fclose(f); return 1; }
    uint8_t *fw = malloc(sz);
    if (fread(fw, 1, sz, f) != (size_t)sz) { perror("fread"); fclose(f); free(fw); return 1; }
    fclose(f);

    printf("Loaded firmware image: %s (%ld bytes)\n", fwpath, sz);
    printf("NOTE: this tool assumes the file is already plaintext; it performs no\n"
           "      decryption of any vendor-encrypted payload (see docs/03_firmware_binary_analysis.md).\n");

    libusb_device_handle *h = open_dev(ctx, LOADER_VID, LOADER_PID);
    if (!h) { free(fw); return 1; }

    printf("Sending AS11Loader-compatible firmware sequence (idx=0x%04x):\n", idx);
    int fail = 0;
    for (size_t i = 0; i < sizeof(LOADER_SEQUENCE)/sizeof(LOADER_SEQUENCE[0]); i++) {
        if (send_fw_chunk(h, fw, (size_t)sz, &LOADER_SEQUENCE[i], idx) != 0) {
            fail = 1;
            break;
        }
    }
    free(fw);
    libusb_release_interface(h, 0);
    libusb_close(h);
    if (fail) {
        fprintf(stderr, "Firmware upload sequence FAILED.\n");
        return 1;
    }
    printf("Firmware upload sequence completed. Re-enumerate (e.g. `hduc_ctl reset`) "
           "and check `lsusb -d 3275:` to see if the device re-appears as the HDTV-C identity.\n");
    return 0;
}

static int parse_hex_bytes(const char *hex, uint8_t *out, size_t maxlen, size_t *outlen)
{
    size_t n = strlen(hex);
    if (n % 2 != 0 || n / 2 > maxlen) return -1;
    for (size_t i = 0; i < n / 2; i++) {
        unsigned int byte;
        if (sscanf(hex + i * 2, "%2x", &byte) != 1) return -1;
        out[i] = (uint8_t)byte;
    }
    *outlen = n / 2;
    return 0;
}

static int cmd_vendor_ctl(libusb_context *ctx, uint16_t vid, uint16_t pid,
                           int dir_in, uint8_t req, uint16_t val, uint16_t idx,
                           uint16_t len, const char *hexdata)
{
    libusb_device_handle *h = open_dev(ctx, vid, pid);
    if (!h) return 1;

    uint8_t buf[4096];
    memset(buf, 0, sizeof(buf));
    size_t datalen = 0;
    if (!dir_in && hexdata) {
        if (parse_hex_bytes(hexdata, buf, sizeof(buf), &datalen) != 0) {
            fprintf(stderr, "error: invalid --data hex string\n");
            libusb_close(h);
            return 1;
        }
        if (datalen < len) len = (uint16_t)datalen;
    }

    uint8_t bmRequestType = LIBUSB_REQUEST_TYPE_VENDOR |
        (dir_in ? LIBUSB_ENDPOINT_IN : LIBUSB_ENDPOINT_OUT) | LIBUSB_RECIPIENT_DEVICE;

    int rc = libusb_control_transfer(h, bmRequestType, req, val, idx, buf, len, CTRL_TIMEOUT_MS);
    printf("control_transfer dir=%s req=0x%02x val=0x%04x idx=0x%04x len=%u -> %d (%s)\n",
           dir_in ? "IN" : "OUT", req, val, idx, len, rc, rc >= 0 ? "OK" : libusb_error_name(rc));
    if (dir_in && rc > 0) {
        printf("data: ");
        for (int i = 0; i < rc; i++) printf("%02x ", buf[i]);
        printf("\n");
    }
    libusb_release_interface(h, 0);
    libusb_close(h);
    return rc >= 0 ? 0 : 1;
}

static void sleep_milliseconds(double milliseconds)
{
    if (milliseconds <= 0.0) return;
    struct timespec delay;
    delay.tv_sec = (time_t)(milliseconds / 1000.0);
    delay.tv_nsec = (long)((milliseconds - (double)delay.tv_sec * 1000.0) * 1000000.0);
    if (delay.tv_nsec < 0) delay.tv_nsec = 0;
    nanosleep(&delay, NULL);
}

static uint64_t monotonic_milliseconds(void)
{
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    return (uint64_t)now.tv_sec * 1000u + (uint64_t)now.tv_nsec / 1000000u;
}

/* Sequence line format, emitted by scripts/extract_u3_replay.py:
 *   delay_ms  in|out  request  wValue  wIndex  wLength  data-or-dash
 *
 * Keeping the USB handle open is material: the U3 tuning sequence contains
 * control requests spaced a few hundred microseconds apart. */
static int run_async_bulk(libusb_context *ctx, libusb_device_handle *h, uint8_t ep,
                          int seconds, int buffers, int size, FILE *out, int start_req,
                          int hduc_post_start);

static int cmd_replay_control(libusb_context *ctx, uint16_t vid, uint16_t pid,
                              const char *seqpath, int dry_run, double scale, int quiet,
                              uint8_t bulk_ep, int bulk_seconds, int bulk_buffers,
                              int bulk_size, const char *bulk_out, int keep_going,
                              int proxy_retries)
{
    FILE *f = strcmp(seqpath, "-") == 0 ? stdin : fopen(seqpath, "r");
    if (!f) { perror("fopen"); return 1; }
    if (scale < 0.0) { fprintf(stderr, "error: --scale must be non-negative\n"); if (f != stdin) fclose(f); return 1; }

    libusb_device_handle *h = NULL;
    if (!dry_run) {
        h = open_dev(ctx, vid, pid);
        if (!h) { if (f != stdin) fclose(f); return 1; }
    }

    char line[1024], direction[8], hexdata[513];
    unsigned int req, val, idx, len;
    double delay_ms;
    int line_no = 0, sent = 0, failures = 0, sequence_started_bulk = 0;
    uint8_t buf[4096];
    while (fgets(line, sizeof(line), f)) {
        line_no++;
        if (line[0] == '#' || line[0] == '\n') continue;
        int fields = sscanf(line, "%lf %7s %x %x %x %u %512s",
                            &delay_ms, direction, &req, &val, &idx, &len, hexdata);
        if (fields != 7 || (strcmp(direction, "in") && strcmp(direction, "out")) ||
            len > sizeof(buf)) {
            fprintf(stderr, "error: malformed sequence line %d\n", line_no);
            failures++;
            break;
        }
        int dir_in = strcmp(direction, "in") == 0;
        size_t datalen = 0;
        memset(buf, 0, sizeof(buf));
        if (!dir_in && strcmp(hexdata, "-") != 0) {
            if (parse_hex_bytes(hexdata, buf, sizeof(buf), &datalen) != 0 || datalen != len) {
                fprintf(stderr, "error: invalid OUT data on sequence line %d\n", line_no);
                failures++;
                break;
            }
        } else if (!dir_in && len != 0) {
            fprintf(stderr, "error: missing OUT data on sequence line %d\n", line_no);
            failures++;
            break;
        }

        if (!dry_run) sleep_milliseconds(delay_ms * scale);
        if (dry_run) {
            if (!quiet) printf("dry-run %8.3fms %s req=0x%02x val=0x%04x idx=0x%04x len=%u\n",
                               delay_ms, direction, req, val, idx, len);
            sent++;
            continue;
        }
        uint8_t bmRequestType = LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_RECIPIENT_DEVICE |
                                (dir_in ? LIBUSB_ENDPOINT_IN : LIBUSB_ENDPOINT_OUT);
        int retry = 0;
        int rc;
        do {
            rc = libusb_control_transfer(h, bmRequestType, (uint8_t)req,
                                         (uint16_t)val, (uint16_t)idx, buf, (uint16_t)len,
                                         CTRL_TIMEOUT_MS);
            if (rc >= 0 || (req != 0x25 && req != 0x26) ||
                (rc != LIBUSB_ERROR_PIPE && rc != LIBUSB_ERROR_TIMEOUT) ||
                retry >= proxy_retries) {
                break;
            }
            retry++;
            if (!quiet) {
                printf("replay retry %d/%d after %s for proxy req=0x%02x; waiting 10ms\n",
                       retry, proxy_retries, libusb_error_name(rc), req);
            }
            /* A control-ENDPOINT stall is cleared by the next SETUP packet.
             * CLEAR_FEATURE is not valid for endpoint zero and was not sent by
             * the Windows driver.  The BDA proxy layer simply waits and retries. */
            sleep_milliseconds(10.0);
        } while (1);
        if (!quiet || rc < 0) {
            printf("replay %8.3fms %s req=0x%02x val=0x%04x idx=0x%04x len=%u -> %d (%s)\n",
                   delay_ms, direction, req, val, idx, len, rc,
                   rc >= 0 ? "OK" : libusb_error_name(rc));
        }
        if (rc < 0) {
            failures++;
            /* The U3 Windows driver treats a proxy STALL as a state-ready
             * poll.  --proxy-retries reproduces that behavior above.  If it
             * remains unavailable, --keep-going may skip it, but never issues
             * a control-endpoint clear-halt. */
            if (keep_going && rc == LIBUSB_ERROR_PIPE) continue;
            break;
        }
        sent++;
        if (req == 0x06) sequence_started_bulk = 1;
    }
    if (f != stdin) fclose(f);
    printf("replay-control: %d command(s), %d failure(s)%s\n", sent, failures,
           dry_run ? " (dry-run)" : "");

    /* After the sequence (which typically ends with the 0x06 stream-start),
     * keep the SAME handle open and pump Bulk IN so the stream the sequence
     * just started is actually read out (closing the handle stops it). */
    int bulk_rc = 0;
    if (h && (!failures || keep_going) && bulk_ep) {
        FILE *out = bulk_out ? fopen(bulk_out, "wb") : NULL;
        if (bulk_out && !out) perror("fopen");
        printf("replay-control: streaming EP 0x%02x on same handle for %ds\n",
               bulk_ep, bulk_seconds);
        /* Capture-derived sequences normally include request 0x06 themselves.
         * Reissuing it here can stop a newly-created HDUC/U3 stream before
         * the first asynchronous bulk URB has been submitted. */
        bulk_rc = run_async_bulk(ctx, h, bulk_ep, bulk_seconds, bulk_buffers, bulk_size, out,
                                 sequence_started_bulk ? 0 : 0x06, 0);
        if (out) fclose(out);
    }
    if (h) {
        libusb_release_interface(h, 0);
        libusb_close(h);
    }
    return (failures || bulk_rc) ? 1 : 0;
}

static int hduc_tune_in(libusb_device_handle *h, uint8_t req, uint16_t val,
                        uint16_t idx, uint16_t len, uint8_t *buf, int dry_run)
{
    memset(buf, 0, len);
    if (dry_run) {
        printf("  IN req=0x%02x value=0x%04x index=0x%04x len=%u\n",
               req, val, idx, len);
        if (len) buf[0] = 1;
        return 0;
    }
    int rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        req, val, idx, buf, len, CTRL_TIMEOUT_MS);
    if (rc != len) {
        fprintf(stderr,
                "tune: req=0x%02x value=0x%04x index=0x%04x returned %d (wanted %u): %s\n",
                req, val, idx, rc, len, rc < 0 ? libusb_error_name(rc) : "short response");
        return -1;
    }
    if (len && buf[0] != 1) {
        fprintf(stderr,
                "tune: req=0x%02x value=0x%04x index=0x%04x device ack=0x%02x\n",
                req, val, idx, buf[0]);
        return -1;
    }
    return 0;
}

/* Some channel-setup requests return register/filter contents rather than the
 * one-byte 0x01 acknowledgement used by the tuner writes. */
static int hduc_tune_read(libusb_device_handle *h, uint8_t req, uint16_t val,
                          uint16_t idx, uint16_t len, uint8_t *buf, int dry_run)
{
    memset(buf, 0, len);
    if (dry_run) {
        printf("  IN req=0x%02x value=0x%04x index=0x%04x len=%u\n",
               req, val, idx, len);
        return 0;
    }
    int rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        req, val, idx, buf, len, CTRL_TIMEOUT_MS);
    if (rc != len) {
        fprintf(stderr,
                "tune: req=0x%02x value=0x%04x index=0x%04x returned %d (wanted %u): %s\n",
                req, val, idx, rc, len, rc < 0 ? libusb_error_name(rc) : "short response");
        return -1;
    }
    return 0;
}

static int hduc_tuner_register(libusb_device_handle *h, uint8_t reg, uint8_t data,
                               int dry_run)
{
    uint8_t buf[8] = {0};
    if (hduc_tune_in(h, 0x0d, 0xfe00, (uint16_t)((reg << 8) | 0xc0), 4,
                     buf, dry_run) != 0)
        return -1;
    if (hduc_tune_in(h, 0x0d, (uint16_t)((data << 8) | 0x03), 0, 2,
                     buf, dry_run) != 0)
        return -1;
    return hduc_tune_in(h, 0x0e, 0x0020, 0, 5, buf, dry_run);
}

static int hduc_tune_on_handle(libusb_device_handle *h, uint16_t channel, int dry_run)
{
    if (channel < 13 || channel > 62) {
        fprintf(stderr, "error: terrestrial physical channel must be 13..62\n");
        return 1;
    }

    /* ARIB/Japanese UHF centre: ch13=473+1/7 MHz, then 6 MHz steps.
     * The official driver programs floor(frequency_kHz * 64 / 1000). */
    uint32_t frequency_khz = 473143u + (uint32_t)(channel - 13) * 6000u;
    uint16_t tuner_word = (uint16_t)(((uint64_t)frequency_khz * 64u) / 1000u);
    printf("tune: terrestrial physical ch%u center=%u kHz tuner_word=0x%04x%s\n",
           channel, frequency_khz, tuner_word, dry_run ? " (dry-run)" : "");

    uint8_t buf[8] = {0};
    int failed = 0;
#define TUNE_IN(req_, val_, idx_, len_) \
    do { if (!failed && hduc_tune_in(h, (req_), (val_), (idx_), (len_), buf, dry_run) != 0) \
             failed = 1; } while (0)

    /* Exact HDTV-C/HDP sequence independently present in the official driver,
     * recfriio Hdp::setChannel, and the x86/x64 Windows USB captures. */
    TUNE_IN(0x02, 0x9d20, 0x0000, 2);
    uint8_t reg_1c = (uint8_t)((buf[1] & 0xfb) | 0x38);
    TUNE_IN(0x03, 0x1c20, reg_1c, 2);
    TUNE_IN(0x03, 0x2520, 0x0000, 2);
    TUNE_IN(0x03, 0x2320, 0x004d, 2);
    TUNE_IN(0x03, 0x1e20, 0x00aa, 2);
    TUNE_IN(0x03, 0x1f20, 0x00a8, 2);

    if (!failed && hduc_tuner_register(h, 0x11, 0x00, dry_run) != 0) failed = 1;
    if (!failed && hduc_tuner_register(h, 0x13, 0x15, dry_run) != 0) failed = 1;
    if (!failed && hduc_tuner_register(h, 0x14, (uint8_t)tuner_word, dry_run) != 0) failed = 1;
    if (!failed && hduc_tuner_register(h, 0x15, (uint8_t)(tuner_word >> 8), dry_run) != 0) failed = 1;
    if (!failed && hduc_tuner_register(h, 0x11, 0x02, dry_run) != 0) failed = 1;

    TUNE_IN(0x03, 0x1e20, 0x00a2, 2);
    TUNE_IN(0x03, 0x1f20, 0x0008, 2);
    TUNE_IN(0x03, 0x0120, 0x0040, 2);
    TUNE_IN(0x03, 0x2320, 0x004c, 2);

    /* Preserve the x64 driver's post-frequency filter setup.  In the known
     * successful trace this precedes the sole stream-start request; omitting
     * it during a retune leaves EP81 with no useful transport packets. */
    uint8_t filter_state[66];
    if (!failed && hduc_tune_read(h, 0x04, 0x0000, 0x0000, 66,
                                  filter_state, dry_run) != 0)
        failed = 1;
    TUNE_IN(0x09, 0x0100, 0x0000, 1);
    if (!failed && !dry_run) sleep_milliseconds(150.0);
    if (!failed && hduc_tune_read(h, 0x05, 0x003f, 0x0007, 3,
                                  filter_state, dry_run) != 0)
        failed = 1;
    if (!failed && hduc_tune_read(h, 0x05, 0x1f41, 0x00ff, 3,
                                  filter_state, dry_run) != 0)
        failed = 1;
    if (!failed && hduc_tune_read(h, 0x05, 0x1f43, 0x00ff, 3,
                                  filter_state, dry_run) != 0)
        failed = 1;
    TUNE_IN(0x02, 0x8220, 0x0000, 2);
    TUNE_IN(0x03, 0x1c20, 0x003a, 2);
#undef TUNE_IN

    if (failed) return 1;
    printf("tune: sequence complete; stream was not started\n");
    return 0;
}

static int cmd_tune(libusb_context *ctx, uint16_t channel, int dry_run)
{
    libusb_device_handle *h = NULL;
    if (!dry_run) {
        h = open_dev(ctx, HDTVC_VID, HDTVC_PID);
        if (!h) return 1;
    }
    int rc = hduc_tune_on_handle(h, channel, dry_run);
    if (h) {
        libusb_release_interface(h, 0);
        libusb_close(h);
    }
    return rc;
}

static int cmd_dump_bulk(libusb_context *ctx, uint8_t ep, int seconds, const char *outpath)
{
    libusb_device_handle *h = open_dev(ctx, HDTVC_VID, HDTVC_PID);
    if (!h) return 1;

    FILE *out = NULL;
    if (outpath) {
        out = fopen(outpath, "wb");
        if (!out) { perror("fopen"); libusb_close(h); return 1; }
    }

    unsigned char buf[16384];
    long total = 0;
    int sync_hits = 0, sync_checks = 0;
    time_t start = time(NULL);
    int transfers = 0, errors = 0;

    printf("Reading EP 0x%02x for %d second(s)...\n", ep, seconds);
    while (difftime(time(NULL), start) < seconds) {
        int transferred = 0;
        int rc = libusb_bulk_transfer(h, ep, buf, sizeof(buf), &transferred, BULK_TIMEOUT_MS);
        transfers++;
        if (rc != 0 && rc != LIBUSB_ERROR_TIMEOUT) {
            fprintf(stderr, "  bulk_transfer error: %s\n", libusb_error_name(rc));
            errors++;
            if (errors > 5) break;
            continue;
        }
        if (transferred > 0) {
            total += transferred;
            if (out) fwrite(buf, 1, transferred, out);
            /* Check for the MPEG-TS sync byte (0x47) every 188 bytes. */
            for (int i = 0; i + 188 <= transferred; i += 188) {
                sync_checks++;
                if (buf[i] == 0x47) sync_hits++;
            }
        }
    }

    printf("Total bytes read: %ld over %d transfer(s) (%d error(s))\n", total, transfers, errors);
    if (sync_checks > 0) {
        printf("MPEG-TS sync byte (0x47) match rate: %d/%d (%.1f%%)\n",
               sync_hits, sync_checks, 100.0 * sync_hits / sync_checks);
        if (sync_hits > sync_checks / 2) {
            printf("-> Looks like real/aligned MPEG-TS data.\n");
        } else {
            printf("-> Does not look like aligned MPEG-TS (no lock / wrong endpoint / needs tuning first).\n");
        }
    } else {
        printf("No data received (endpoint idle - device likely not streaming).\n");
    }

    if (out) fclose(out);
    libusb_release_interface(h, 0);
    libusb_close(h);
    return 0;
}

struct async_bulk_ctx {
    libusb_context *usb_ctx;
    FILE *out;
    int running;
    int active;
    int errors;
    long total_bytes;
    long completed;
    long payloads;
    long ts_candidates;
    long binary_symbols;
    int stop_on_output_error;
    int output_failed;
};

struct async_bulk_slot {
    struct async_bulk_ctx *ctx;
    struct libusb_transfer *transfer;
    unsigned char *buffer;
};

static volatile sig_atomic_t keepalive_running = 1;
static volatile sig_atomic_t async_bulk_running = 1;
static volatile sig_atomic_t server_running = 1;
static int run_hduc_keepalive_on_handle(libusb_device_handle *h, int seconds,
                                         int interval_ms);

static void async_bulk_signal_handler(int signal_number)
{
    (void)signal_number;
    async_bulk_running = 0;
}

static void server_signal_handler(int signal_number)
{
    (void)signal_number;
    server_running = 0;
    async_bulk_running = 0;
}

static const char *transfer_status_name(enum libusb_transfer_status status)
{
    switch (status) {
    case LIBUSB_TRANSFER_COMPLETED: return "completed";
    case LIBUSB_TRANSFER_ERROR: return "error";
    case LIBUSB_TRANSFER_TIMED_OUT: return "timed out";
    case LIBUSB_TRANSFER_CANCELLED: return "cancelled";
    case LIBUSB_TRANSFER_STALL: return "stall";
    case LIBUSB_TRANSFER_NO_DEVICE: return "no device";
    case LIBUSB_TRANSFER_OVERFLOW: return "overflow";
    default: return "unknown";
    }
}

static void inspect_async_payload(struct async_bulk_ctx *ctx, const unsigned char *buf, int len)
{
    if (len <= 0) return;
    ctx->payloads++;
    ctx->total_bytes += len;
    for (int i = 0; i < len; i++) {
        if (buf[i] == 0 || buf[i] == 1) ctx->binary_symbols++;
    }
    /* Three aligned 0x47 bytes are enough to make a useful conservative hint.
     * Full TS framing remains the caller's responsibility. */
    for (int off = 0; off + 376 < len; off++) {
        if (buf[off] == 0x47 && buf[off + 188] == 0x47 && buf[off + 376] == 0x47) {
            ctx->ts_candidates++;
            break;
        }
    }
    if (ctx->out && fwrite(buf, 1, (size_t)len, ctx->out) != (size_t)len) {
        fprintf(stderr, "  async bulk output closed: %s\n",
                errno ? strerror(errno) : "short write");
        ctx->output_failed = 1;
        ctx->out = NULL;
        if (ctx->stop_on_output_error) {
            ctx->errors++;
            ctx->running = 0;
        }
    }
}

static void LIBUSB_CALL async_bulk_callback(struct libusb_transfer *transfer)
{
    struct async_bulk_slot *slot = transfer->user_data;
    struct async_bulk_ctx *ctx = slot->ctx;
    int resubmit = 0;

    if (transfer->status == LIBUSB_TRANSFER_COMPLETED) {
        ctx->completed++;
        inspect_async_payload(ctx, transfer->buffer, transfer->actual_length);
        resubmit = ctx->running;
    } else if (transfer->status == LIBUSB_TRANSFER_TIMED_OUT) {
        resubmit = ctx->running;
    } else if (transfer->status != LIBUSB_TRANSFER_CANCELLED) {
        fprintf(stderr, "  async bulk error: %s\n", transfer_status_name(transfer->status));
        ctx->errors++;
    }

    if (resubmit) {
        int rc = libusb_submit_transfer(transfer);
        if (rc == 0) return;
        fprintf(stderr, "  async bulk resubmit failed: %s\n", libusb_error_name(rc));
        ctx->errors++;
    }
    ctx->active--;
}

static int hduc_start_stream(libusb_device_handle *h, int hduc_post_start)
{
    unsigned char response[2] = {0};
    int rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x06, 0, 0, response, 1, CTRL_TIMEOUT_MS);
    printf("start bulk req=0x06 -> %d (resp=0x%02x)\n", rc, response[0]);
    if (rc != 1 || response[0] != 1) return 1;
    if (!hduc_post_start) return 0;

    int rc4 = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x04, 0x0040, 0, response, 2, CTRL_TIMEOUT_MS);
    int rc5 = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x05, 0x0f40, 0, response, 2, CTRL_TIMEOUT_MS);
    printf("HDUC post-start reqs: 0x04 -> %d, 0x05 -> %d\n", rc4, rc5);
    return (rc4 == 2 && rc5 == 2) ? 0 : 1;
}

/* Queue asynchronous Bulk IN reads on an ALREADY-OPEN handle and pump the
 * event loop for `seconds`.  Does not open/close the handle, so the caller can
 * keep the same handle that started streaming (the U3 stops when that handle
 * closes).  Returns the error count. */
static int run_async_bulk(libusb_context *ctx, libusb_device_handle *h, uint8_t ep,
                          int seconds, int buffers, int size, FILE *out, int start_req,
                          int hduc_post_start)
{
    async_bulk_running = 1;
    struct async_bulk_ctx state = {
        .usb_ctx = ctx, .out = out, .running = 1, .stop_on_output_error = 1,
    };
    struct async_bulk_slot *slots = calloc((size_t)buffers, sizeof(*slots));
    if (!slots) { fprintf(stderr, "error: out of memory\n"); return 1; }

    int initialized = 0;
    for (int i = 0; i < buffers; i++) {
        slots[i].ctx = &state;
        slots[i].buffer = malloc((size_t)size);
        slots[i].transfer = libusb_alloc_transfer(0);
        if (!slots[i].buffer || !slots[i].transfer) break;
        libusb_fill_bulk_transfer(slots[i].transfer, h, ep, slots[i].buffer, size,
                                  async_bulk_callback, &slots[i], BULK_TIMEOUT_MS);
        int rc = libusb_submit_transfer(slots[i].transfer);
        if (rc != 0) {
            fprintf(stderr, "  async bulk submit failed: %s\n", libusb_error_name(rc));
            break;
        }
        state.active++;
        initialized++;
    }
    if (initialized != buffers) {
        state.running = 0;
        for (int i = 0; i < initialized; i++) libusb_cancel_transfer(slots[i].transfer);
    }

    if (seconds == 0)
        printf("Queued %d asynchronous reads on EP 0x%02x (%d bytes each) until signal.\n",
               initialized, ep, size);
    else
        printf("Queued %d asynchronous reads on EP 0x%02x (%d bytes each) for %d second(s).\n",
               initialized, ep, size, seconds);

    /* Issue the stream-start vendor request (0x06) AFTER the Bulk IN reads are
     * queued, mirroring the Windows driver which pre-queues URBs then starts.
     * If sent before reads exist, the first burst has no receiver and the
     * endpoint goes idle. */
    if (start_req && state.running) {
        if (start_req == 0x06) {
            if (hduc_start_stream(h, hduc_post_start) != 0) state.running = 0;
        } else {
            unsigned char response[1] = {0};
            int rc = libusb_control_transfer(
                h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
                (uint8_t)start_req, 0, 0, response, 1, CTRL_TIMEOUT_MS);
            printf("start bulk req=0x%02x -> %d (resp=0x%02x)\n",
                   start_req, rc, response[0]);
            if (rc < 0) state.running = 0;
        }
    }

    /* During streaming Windows keeps a few control polls alive:
     *   - bRequest 0x00 len=33  ~10 Hz  (event/heartbeat)
     *   - bRequest 0x22 val=0/1 ~0.2 Hz (seen every ~5 s in hducgood)
     *   - bRequest 0x02 status  occasional (0x045a / 0x8b20)
     * HDUC runtime otherwise tends to drop ~30-40 s after re-enumeration
     * when these stop (docs/33, docs/55).  0x00 alone is already a big help;
     * the extras match the capture more closely for longer captures. */
    unsigned char pbuf[33];
    unsigned char sbuf2[4];
    time_t end = seconds ? time(NULL) + seconds : 0;
    time_t next_22 = time(NULL) + 5;
    time_t next_stat = time(NULL) + 1;
    while (state.active > 0 && state.running && async_bulk_running &&
           (!end || time(NULL) < end)) {
        struct timeval timeout = { .tv_sec = 0, .tv_usec = 100000 };
        libusb_handle_events_timeout_completed(ctx, &timeout, NULL);
        libusb_control_transfer(
            h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
            0x00, 0, 0, pbuf, sizeof(pbuf), 100);
        time_t now = time(NULL);
        if (now >= next_22) {
            libusb_control_transfer(
                h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
                0x22, 0x0000, 0, sbuf2, 1, 100);
            libusb_control_transfer(
                h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
                0x22, 0x0001, 0, sbuf2, 1, 100);
            next_22 = now + 5;
        }
        if (now >= next_stat) {
            libusb_control_transfer(
                h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
                0x02, 0x045a, 0, sbuf2, 2, 100);
            libusb_control_transfer(
                h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
                0x02, 0x8b20, 0, sbuf2, 4, 100);
            next_stat = now + 1;
        }
        if (state.errors > 5) state.running = 0;
    }
    state.running = 0;
    for (int i = 0; i < initialized; i++) {
        if (slots[i].transfer) libusb_cancel_transfer(slots[i].transfer);
    }
    while (state.active > 0) {
        struct timeval timeout = { .tv_sec = 0, .tv_usec = 250000 };
        libusb_handle_events_timeout_completed(ctx, &timeout, NULL);
    }

    printf("Async bulk result: completions=%ld payloads=%ld bytes=%ld errors=%d\n",
           state.completed, state.payloads, state.total_bytes, state.errors);
    if (state.total_bytes > 0) {
        printf("  binary-symbol bytes (00/01): %ld/%ld; TS sync candidates: %ld\n",
               state.binary_symbols, state.total_bytes, state.ts_candidates);
    } else {
        printf("  No payload: the endpoint is idle or streaming was not initialized.\n");
    }
    for (int i = 0; i < buffers; i++) {
        if (slots[i].transfer) libusb_free_transfer(slots[i].transfer);
        free(slots[i].buffer);
    }
    free(slots);
    return state.errors ? 1 : 0;
}

static int cmd_async_bulk(libusb_context *ctx, uint16_t vid, uint16_t pid, uint8_t ep,
                          int seconds, int buffers, int size, const char *outpath,
                          int start_req, int hduc_post_start, int hold_after,
                          const char *ready_file)
{
    if (!(ep & LIBUSB_ENDPOINT_IN) || seconds < 0 || buffers < 1 ||
        buffers > ASYNC_MAX_BUFFERS || size < 1 || size > ASYNC_MAX_TRANSFER) {
        fprintf(stderr, "error: invalid async-bulk arguments\n");
        return 1;
    }
    libusb_device_handle *h = open_dev(ctx, vid, pid);
    if (!h) return 1;

    signal(SIGINT, async_bulk_signal_handler);
    signal(SIGTERM, async_bulk_signal_handler);

    FILE *out = NULL;
    if (outpath) {
        out = fopen(outpath, "wb");
        if (!out) { perror("fopen"); libusb_release_interface(h, 0); libusb_close(h); return 1; }
    }
    int rc = run_async_bulk(ctx, h, ep, seconds, buffers, size, out, start_req,
                            hduc_post_start);
    if (out) {
        fflush(out);
        fclose(out);
        out = NULL;
    }
    if (ready_file) {
        FILE *ready = fopen(ready_file, "w");
        if (!ready) {
            perror("ready-file fopen");
            rc = 1;
        } else {
            fprintf(ready, "capture_exit=%d\n", rc);
            fclose(ready);
        }
    }
    if (hduc_post_start && hold_after >= 0 && rc == 0) {
        printf("Capture complete; retaining the same HDUC USB handle.\n");
        fflush(stdout);
        if (run_hduc_keepalive_on_handle(h, hold_after, 100) != 0) rc = 1;
    }
    libusb_release_interface(h, 0);
    libusb_close(h);
    return rc;
}

static int u3_status_read(libusb_device_handle *h, uint16_t value, unsigned char *buf, uint16_t len)
{
    return libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x02, value, 0, buf, len, CTRL_TIMEOUT_MS);
}

static void keepalive_signal_handler(int signal_number)
{
    (void)signal_number;
    keepalive_running = 0;
}

static int hduc_heartbeat(libusb_device_handle *h, int send_slow_polls)
{
    unsigned char event[33] = {0};
    unsigned char status[4] = {0};
    int failures = 0;
    int rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x00, 0, 0, event, sizeof(event), 250);
    if (rc != (int)sizeof(event)) failures++;
    if (!send_slow_polls) return failures;

    rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x22, 0x0000, 0, status, 1, 250);
    if (rc != 1) failures++;
    rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x22, 0x0001, 0, status, 1, 250);
    if (rc != 1) failures++;
    rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x02, 0x045a, 0, status, 2, 250);
    if (rc != 2) failures++;
    rc = libusb_control_transfer(
        h, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN | LIBUSB_RECIPIENT_DEVICE,
        0x02, 0x8b20, 0, status, 4, 250);
    if (rc != 4) failures++;
    return failures;
}

static int send_socket_text(int fd, const char *text)
{
    size_t left = strlen(text);
    while (left) {
        ssize_t n = send(fd, text, left, MSG_NOSIGNAL);
        if (n < 0 && errno == EINTR) continue;
        if (n <= 0) return -1;
        text += n;
        left -= (size_t)n;
    }
    return 0;
}

static int read_socket_line(int fd, char *line, size_t capacity)
{
    size_t used = 0;
    while (used + 1 < capacity) {
        char ch;
        ssize_t n = recv(fd, &ch, 1, 0);
        if (n < 0 && errno == EINTR) continue;
        if (n <= 0) return -1;
        if (ch == '\n') {
            line[used] = '\0';
            return 0;
        }
        line[used++] = ch;
    }
    line[capacity - 1] = '\0';
    return -1;
}

static int cmd_hduc_server(libusb_context *ctx, const char *socket_path,
                            uint16_t initial_channel)
{
    enum { SERVER_BUFFERS = 8, SERVER_TRANSFER_SIZE = 8192 };
    if (!socket_path || !*socket_path ||
        strlen(socket_path) >= sizeof(((struct sockaddr_un *)0)->sun_path)) {
        fprintf(stderr, "error: hduc-server requires a shorter --socket PATH\n");
        return 1;
    }
    if (initial_channel < 13 || initial_channel > 62) {
        fprintf(stderr, "error: hduc-server requires --channel 13..62\n");
        return 1;
    }

    libusb_device_handle *h = open_dev(ctx, HDTVC_VID, HDTVC_PID);
    if (!h) return 1;

    int listen_fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (listen_fd < 0) {
        perror("socket");
        libusb_release_interface(h, 0);
        libusb_close(h);
        return 1;
    }

    struct stat st;
    if (lstat(socket_path, &st) == 0) {
        if (!S_ISSOCK(st.st_mode)) {
            fprintf(stderr, "error: refusing to replace non-socket path %s\n", socket_path);
            close(listen_fd);
            libusb_release_interface(h, 0);
            libusb_close(h);
            return 1;
        }
        if (unlink(socket_path) != 0) {
            perror("unlink stale socket");
            close(listen_fd);
            libusb_release_interface(h, 0);
            libusb_close(h);
            return 1;
        }
    } else if (errno != ENOENT) {
        perror("lstat socket path");
        close(listen_fd);
        libusb_release_interface(h, 0);
        libusb_close(h);
        return 1;
    }

    struct sockaddr_un address;
    memset(&address, 0, sizeof(address));
    address.sun_family = AF_UNIX;
    strncpy(address.sun_path, socket_path, sizeof(address.sun_path) - 1);
    if (bind(listen_fd, (struct sockaddr *)&address, sizeof(address)) != 0 ||
        listen(listen_fd, 4) != 0) {
        perror("bind/listen");
        close(listen_fd);
        libusb_release_interface(h, 0);
        libusb_close(h);
        return 1;
    }
    chmod(socket_path, 0660);

    struct async_bulk_ctx stream = {
        .usb_ctx = ctx, .running = 1, .stop_on_output_error = 0,
    };
    struct async_bulk_slot *slots = calloc(SERVER_BUFFERS, sizeof(*slots));
    if (!slots) {
        fprintf(stderr, "error: out of memory\n");
        close(listen_fd);
        unlink(socket_path);
        libusb_release_interface(h, 0);
        libusb_close(h);
        return 1;
    }
    int initialized = 0;
    for (int i = 0; i < SERVER_BUFFERS; i++) {
        slots[i].ctx = &stream;
        slots[i].buffer = malloc(SERVER_TRANSFER_SIZE);
        slots[i].transfer = libusb_alloc_transfer(0);
        if (!slots[i].buffer || !slots[i].transfer) break;
        libusb_fill_bulk_transfer(slots[i].transfer, h, 0x81, slots[i].buffer,
                                  SERVER_TRANSFER_SIZE, async_bulk_callback,
                                  &slots[i], BULK_TIMEOUT_MS);
        int rc = libusb_submit_transfer(slots[i].transfer);
        if (rc != 0) {
            fprintf(stderr, "server bulk submit failed: %s\n", libusb_error_name(rc));
            break;
        }
        stream.active++;
        initialized++;
    }
    if (initialized != SERVER_BUFFERS || hduc_start_stream(h, 1) != 0) {
        stream.running = 0;
        for (int i = 0; i < initialized; i++) libusb_cancel_transfer(slots[i].transfer);
        while (stream.active > 0) {
            struct timeval timeout = { .tv_sec = 0, .tv_usec = 250000 };
            libusb_handle_events_timeout_completed(ctx, &timeout, NULL);
        }
        for (int i = 0; i < SERVER_BUFFERS; i++) {
            if (slots[i].transfer) libusb_free_transfer(slots[i].transfer);
            free(slots[i].buffer);
        }
        free(slots);
        close(listen_fd);
        unlink(socket_path);
        libusb_release_interface(h, 0);
        libusb_close(h);
        return 1;
    }

    signal(SIGINT, server_signal_handler);
    signal(SIGTERM, server_signal_handler);
    signal(SIGPIPE, SIG_IGN);
    server_running = 1;
    async_bulk_running = 1;
    uint64_t now_ms = monotonic_milliseconds();
    uint64_t next_heartbeat = now_ms;
    uint64_t next_slow = now_ms;
    uint64_t next_report = now_ms + 10000;
    unsigned long heartbeats = 0;
    int total_failures = 0;
    int consecutive_failures = 0;
    uint16_t current_channel = initial_channel;
    int client_fd = -1;
    FILE *client_output = NULL;
    uint64_t client_deadline = 0;
    long client_start_bytes = 0;

    printf("HDUC server ready: socket=%s bus=%d port=%d channel=%u; "
           "EP81 remains queued between recordings\n",
           socket_path, selected_bus, selected_port, current_channel);
    fflush(stdout);

    while (server_running && stream.active > 0 && stream.errors <= 5) {
        struct timeval event_timeout = { .tv_sec = 0, .tv_usec = 50000 };
        libusb_handle_events_timeout_completed(ctx, &event_timeout, NULL);
        now_ms = monotonic_milliseconds();

        if (now_ms >= next_heartbeat) {
            int failures = hduc_heartbeat(h, now_ms >= next_slow);
            heartbeats++;
            total_failures += failures;
            consecutive_failures = failures ? consecutive_failures + 1 : 0;
            next_heartbeat = now_ms + 100;
            if (now_ms >= next_slow) next_slow = now_ms + 5000;
        }
        if (now_ms >= next_report) {
            printf("HDUC server: heartbeats=%lu failures=%d bulk_bytes=%ld client=%s\n",
                   heartbeats, total_failures, stream.total_bytes,
                   client_output ? "recording" : "idle");
            fflush(stdout);
            next_report = now_ms + 10000;
        }
        if (consecutive_failures >= 5) {
            fprintf(stderr, "HDUC server: device stopped responding\n");
            break;
        }

        if (client_output && (stream.output_failed ||
                              (client_deadline && now_ms >= client_deadline))) {
            stream.out = NULL;
            fflush(client_output);
            fclose(client_output);
            client_output = NULL;
            shutdown(client_fd, SHUT_RDWR);
            close(client_fd);
            client_fd = -1;
            printf("HDUC server client complete: bytes=%ld output_error=%d\n",
                   stream.total_bytes - client_start_bytes, stream.output_failed);
            stream.output_failed = 0;
            client_deadline = 0;
            fflush(stdout);
        }
        if (client_output) continue;

        struct pollfd descriptor = { .fd = listen_fd, .events = POLLIN };
        int ready = poll(&descriptor, 1, 0);
        if (ready < 0 && errno != EINTR) {
            perror("poll");
            break;
        }
        if (ready <= 0 || !(descriptor.revents & POLLIN)) continue;

        client_fd = accept(listen_fd, NULL, NULL);
        if (client_fd < 0) {
            if (errno != EINTR) perror("accept");
            continue;
        }
        struct timeval command_timeout = { .tv_sec = 5, .tv_usec = 0 };
        struct timeval output_timeout = { .tv_sec = 2, .tv_usec = 0 };
        int output_buffer = 1024 * 1024;
        setsockopt(client_fd, SOL_SOCKET, SO_RCVTIMEO,
                   &command_timeout, sizeof(command_timeout));
        setsockopt(client_fd, SOL_SOCKET, SO_SNDTIMEO,
                   &output_timeout, sizeof(output_timeout));
        setsockopt(client_fd, SOL_SOCKET, SO_SNDBUF,
                   &output_buffer, sizeof(output_buffer));

        char command[128];
        unsigned int requested_channel = 0;
        int seconds = -1;
        char extra = '\0';
        if (read_socket_line(client_fd, command, sizeof(command)) != 0 ||
            sscanf(command, "RECORD %u %d %c", &requested_channel, &seconds, &extra) != 2 ||
            requested_channel < 13 || requested_channel > 62 || seconds < 0) {
            send_socket_text(client_fd, "ERR expected RECORD channel(13..62) seconds(>=0)\n");
            close(client_fd);
            client_fd = -1;
            continue;
        }

        if (requested_channel != current_channel) {
            printf("HDUC server retune: ch%u -> ch%u\n",
                   current_channel, requested_channel);
            fflush(stdout);
            if (hduc_tune_on_handle(h, (uint16_t)requested_channel, 0) != 0) {
                send_socket_text(client_fd, "ERR tune failed\n");
                close(client_fd);
                client_fd = -1;
                continue;
            }
            uint64_t settle_end = monotonic_milliseconds() + 1000;
            while (server_running && monotonic_milliseconds() < settle_end) {
                struct timeval timeout = { .tv_sec = 0, .tv_usec = 50000 };
                libusb_handle_events_timeout_completed(ctx, &timeout, NULL);
                uint64_t settle_now = monotonic_milliseconds();
                if (settle_now >= next_heartbeat) {
                    int failures = hduc_heartbeat(h, settle_now >= next_slow);
                    heartbeats++;
                    total_failures += failures;
                    next_heartbeat = settle_now + 100;
                    if (settle_now >= next_slow) next_slow = settle_now + 5000;
                }
            }
            /* Frequency programming stops EP81.  The restart succeeds only
             * after hduc_tune_on_handle has restored the x64 PID-filter state;
             * issuing 0x06 without that state yields a short residual burst
             * and an idle endpoint.  Keep the existing URBs queued, settle,
             * then use the same start/post-start requests as Windows. */
            if (!server_running || hduc_start_stream(h, 1) != 0) {
                send_socket_text(client_fd, "ERR stream restart failed\n");
                close(client_fd);
                client_fd = -1;
                continue;
            }
            current_channel = (uint16_t)requested_channel;
        }

        if (send_socket_text(client_fd, "OK\n") != 0) {
            close(client_fd);
            client_fd = -1;
            continue;
        }
        int output_fd = dup(client_fd);
        client_output = output_fd >= 0 ? fdopen(output_fd, "wb") : NULL;
        if (!client_output) {
            if (output_fd >= 0) close(output_fd);
            close(client_fd);
            client_fd = -1;
            continue;
        }
        setvbuf(client_output, NULL, _IOFBF, 64 * 1024);
        stream.output_failed = 0;
        stream.out = client_output;
        client_start_bytes = stream.total_bytes;
        client_deadline = seconds ? monotonic_milliseconds() + (uint64_t)seconds * 1000u : 0;
        if (seconds)
            printf("HDUC server client: channel=%u seconds=%d\n",
                   requested_channel, seconds);
        else
            printf("HDUC server client: channel=%u seconds=until-disconnect\n",
                   requested_channel);
        fflush(stdout);
    }

    stream.out = NULL;
    if (client_output) {
        fflush(client_output);
        fclose(client_output);
    }
    if (client_fd >= 0) close(client_fd);
    stream.running = 0;
    for (int i = 0; i < initialized; i++) libusb_cancel_transfer(slots[i].transfer);
    while (stream.active > 0) {
        struct timeval timeout = { .tv_sec = 0, .tv_usec = 250000 };
        libusb_handle_events_timeout_completed(ctx, &timeout, NULL);
    }
    for (int i = 0; i < SERVER_BUFFERS; i++) {
        if (slots[i].transfer) libusb_free_transfer(slots[i].transfer);
        free(slots[i].buffer);
    }
    free(slots);
    close(listen_fd);
    unlink(socket_path);
    libusb_release_interface(h, 0);
    libusb_close(h);
    printf("HDUC server stopped: heartbeats=%lu failures=%d bulk_bytes=%ld errors=%d\n",
           heartbeats, total_failures, stream.total_bytes, stream.errors);
    return (consecutive_failures >= 5 || stream.errors > 5) ? 1 : 0;
}

static int run_hduc_keepalive_on_handle(libusb_device_handle *h, int seconds,
                                         int interval_ms)
{
    signal(SIGINT, keepalive_signal_handler);
    signal(SIGTERM, keepalive_signal_handler);
    keepalive_running = 1;
    time_t started = time(NULL);
    time_t deadline = seconds ? started + seconds : 0;
    time_t next_slow = started;
    time_t next_report = started + 10;
    unsigned long heartbeats = 0;
    int total_failures = 0;
    int consecutive_failures = 0;
    printf("HDUC keepalive active: interval=%dms duration=%s\n",
           interval_ms, seconds ? "bounded" : "until signal");
    fflush(stdout);

    while (keepalive_running && (!deadline || time(NULL) < deadline)) {
        time_t now = time(NULL);
        int failures = hduc_heartbeat(h, now >= next_slow);
        heartbeats++;
        total_failures += failures;
        consecutive_failures = failures ? consecutive_failures + 1 : 0;
        if (now >= next_slow) next_slow = now + 5;
        if (now >= next_report) {
            printf("HDUC keepalive: elapsed=%lds heartbeats=%lu failures=%d\n",
                   (long)(now - started), heartbeats, total_failures);
            fflush(stdout);
            next_report = now + 10;
        }
        if (consecutive_failures >= 5) {
            fprintf(stderr, "HDUC keepalive: device stopped responding\n");
            break;
        }
        sleep_milliseconds((double)interval_ms);
    }
    printf("HDUC keepalive stopped: elapsed=%lds heartbeats=%lu failures=%d\n",
           (long)(time(NULL) - started), heartbeats, total_failures);
    return consecutive_failures >= 5 ? 1 : 0;
}

static int cmd_hduc_keepalive(libusb_context *ctx, int seconds, int interval_ms)
{
    if (seconds < 0 || interval_ms < 20) {
        fprintf(stderr, "error: hduc-keepalive requires seconds >= 0 and interval >= 20 ms\n");
        return 1;
    }
    libusb_device_handle *h = open_dev(ctx, HDTVC_VID, HDTVC_PID);
    if (!h) return 1;
    int rc = run_hduc_keepalive_on_handle(h, seconds, interval_ms);
    libusb_release_interface(h, 0);
    libusb_close(h);
    return rc;
}

static int cmd_u3_monitor(libusb_context *ctx, uint16_t vid, uint16_t pid,
                          int seconds, int interval_ms)
{
    if (seconds < 1 || interval_ms < 1) {
        fprintf(stderr, "error: invalid u3-monitor arguments\n");
        return 1;
    }
    libusb_device_handle *h = open_dev(ctx, vid, pid);
    if (!h) return 1;
    time_t end = time(NULL) + seconds;
    int failures = 0, sample = 0;
    printf("Read-only U3 status monitor for %d second(s), every %d ms:\n", seconds, interval_ms);
    while (time(NULL) < end) {
        unsigned char tuner_state[4] = {0};
        unsigned char stream_state[2] = {0};
        int a = u3_status_read(h, 0x8b30, tuner_state, sizeof(tuner_state));
        int b = u3_status_read(h, 0xc332, stream_state, sizeof(stream_state));
        printf("  #%d  8b30=", ++sample);
        if (a == 4) printf("%02x %02x %02x %02x", tuner_state[0], tuner_state[1], tuner_state[2], tuner_state[3]);
        else { printf("<%d %s>", a, a < 0 ? libusb_error_name(a) : "short"); failures++; }
        printf("  c332=");
        if (b == 2) printf("%02x %02x", stream_state[0], stream_state[1]);
        else { printf("<%d %s>", b, b < 0 ? libusb_error_name(b) : "short"); failures++; }
        printf("\n");
        sleep_milliseconds((double)interval_ms);
    }
    libusb_release_interface(h, 0);
    libusb_close(h);
    return failures ? 1 : 0;
}

int main(int argc, char **argv)
{
    if (argc < 2) { print_usage(argv[0]); return 1; }

    uint16_t vid = LOADER_VID, pid = LOADER_PID;
    uint16_t idx = LOADER_IDX_DEFAULT;
    int dir_in = -1;
    uint8_t req = 0;
    uint16_t val = 0, wlen = 0;
    const char *hexdata = NULL;
    const char *fwpath = NULL;
    const char *cmd = argv[1];
    uint16_t channel = 0;
    uint8_t ep = 0;
    int seconds = 5;
    const char *outpath = NULL;
    int buffers = 8;
    int bulk_size = 8192;
    int start_req = 0;
    int hduc_post_start = 0;
    int hold_after = -1;
    int keep_going = 0;
    int proxy_retries = 0;
    int interval_ms = 1000;
    const char *seqpath = NULL;
    const char *ready_file = NULL;
    const char *socket_path = NULL;
    int dry_run = 0, quiet = 0;
    double scale = 1.0;

    for (int i = 2; i < argc; i++) {
        if (!strcmp(argv[i], "--vid") && i + 1 < argc) vid = (uint16_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--pid") && i + 1 < argc) pid = (uint16_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--bus") && i + 1 < argc) selected_bus = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--port") && i + 1 < argc) selected_port = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--idx") && i + 1 < argc) idx = (uint16_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--dir") && i + 1 < argc) dir_in = !strcmp(argv[++i], "in");
        else if (!strcmp(argv[i], "--req") && i + 1 < argc) req = (uint8_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--val") && i + 1 < argc) val = (uint16_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--len") && i + 1 < argc) wlen = (uint16_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--data") && i + 1 < argc) hexdata = argv[++i];
        else if (!strcmp(argv[i], "--channel") && i + 1 < argc) channel = (uint16_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--ep") && i + 1 < argc) ep = (uint8_t)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--seconds") && i + 1 < argc) seconds = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--buffers") && i + 1 < argc) buffers = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--size") && i + 1 < argc) bulk_size = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--start") && i + 1 < argc) start_req = (int)strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--hduc-post-start")) hduc_post_start = 1;
        else if (!strcmp(argv[i], "--hold-after") && i + 1 < argc) hold_after = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--ready-file") && i + 1 < argc) ready_file = argv[++i];
        else if (!strcmp(argv[i], "--socket") && i + 1 < argc) socket_path = argv[++i];
        else if (!strcmp(argv[i], "--keep-going")) keep_going = 1;
        else if (!strcmp(argv[i], "--proxy-retries") && i + 1 < argc) proxy_retries = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--interval-ms") && i + 1 < argc) interval_ms = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--out") && i + 1 < argc) outpath = argv[++i];
        else if (!strcmp(argv[i], "--file") && i + 1 < argc) seqpath = argv[++i];
        else if (!strcmp(argv[i], "--dry-run")) dry_run = 1;
        else if (!strcmp(argv[i], "--quiet")) quiet = 1;
        else if (!strcmp(argv[i], "--scale") && i + 1 < argc) scale = strtod(argv[++i], NULL);
        else if (!fwpath && argv[i][0] != '-') fwpath = argv[i];
    }

    libusb_context *ctx = NULL;
    if (libusb_init(&ctx) != 0) {
        fprintf(stderr, "libusb_init failed\n");
        return 1;
    }

    int rc;
    if (!strcmp(cmd, "info")) {
        rc = cmd_info(ctx, vid, pid);
    } else if (!strcmp(cmd, "loader-upload")) {
        if (!fwpath) { print_usage(argv[0]); rc = 1; }
        else rc = cmd_loader_upload(ctx, fwpath, idx);
    } else if (!strcmp(cmd, "vendor-ctl")) {
        if (dir_in == -1) { fprintf(stderr, "error: --dir in|out required\n"); rc = 1; }
        else rc = cmd_vendor_ctl(ctx, vid, pid, dir_in, req, val, idx, wlen, hexdata);
    } else if (!strcmp(cmd, "replay-control")) {
        if (!seqpath) { fprintf(stderr, "error: --file SEQUENCE required\n"); rc = 1; }
        else rc = cmd_replay_control(ctx, vid, pid, seqpath, dry_run, scale, quiet,
                                     ep, seconds, buffers, bulk_size, outpath, keep_going,
                                     proxy_retries);
    } else if (!strcmp(cmd, "reset")) {
        rc = cmd_reset(ctx, vid, pid);
    } else if (!strcmp(cmd, "tune")) {
        if (channel == 0) { fprintf(stderr, "error: --channel N required\n"); rc = 1; }
        else rc = cmd_tune(ctx, channel, dry_run);
    } else if (!strcmp(cmd, "dump-bulk")) {
        if (ep == 0) { fprintf(stderr, "error: --ep 0x81|0x82 required\n"); rc = 1; }
        else rc = cmd_dump_bulk(ctx, ep, seconds, outpath);
    } else if (!strcmp(cmd, "async-bulk")) {
        if (ep == 0) { fprintf(stderr, "error: --ep 0x81|0x82 required\n"); rc = 1; }
        else rc = cmd_async_bulk(ctx, vid, pid, ep, seconds, buffers, bulk_size, outpath,
                                 start_req, hduc_post_start, hold_after, ready_file);
    } else if (!strcmp(cmd, "u3-monitor")) {
        rc = cmd_u3_monitor(ctx, vid, pid, seconds, interval_ms);
    } else if (!strcmp(cmd, "hduc-keepalive")) {
        rc = cmd_hduc_keepalive(ctx, seconds, interval_ms);
    } else if (!strcmp(cmd, "hduc-server")) {
        rc = cmd_hduc_server(ctx, socket_path, channel);
    } else {
        print_usage(argv[0]);
        rc = 1;
    }

    libusb_exit(ctx);
    return rc;
}
