#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 bamboo
"""Probe U3 BS/CS physical transponders and emit Mirakurun channel YAML.

This uses the installed ``recpt1-u3`` client and the already-running ``u3d``
daemon.  It intentionally does not use B25: a CRC-valid PAT is enough to
determine whether a physical transponder is receivable.  Keep Mirakurun
stopped while running it, because one U3 has one tuner path.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path


CHANNELS = (
    *(f"BS{channel:02d}_0" for channel in range(1, 24, 2)),
    *(f"CS{channel}" for channel in range(2, 25, 2)),
)
PAT_RE = re.compile(r"PAT programs=([0-9,]+)")


def mirakurun_item(channel: str) -> tuple[str, str]:
    if channel.startswith("BS"):
        return "BS", f"U3-{channel.split('_', 1)[0]}"
    return "CS", f"U3-{channel}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--socket", default="/run/asie5607/u3.sock")
    parser.add_argument("--client", type=Path, default=Path(__file__).with_name("recpt1-u3"))
    parser.add_argument("--seconds", type=int, default=2)
    parser.add_argument("--timeout", type=int, default=6)
    args = parser.parse_args()
    if args.seconds < 1 or args.timeout <= args.seconds:
        parser.error("timeout must be greater than seconds, and seconds must be positive")

    detected: list[tuple[str, int, str]] = []
    with tempfile.TemporaryDirectory(prefix="asie5607-u3-probe-") as temporary:
        tempdir = Path(temporary)
        for channel in CHANNELS:
            capture = tempdir / f"{channel}.ts"
            command = [str(args.client), "--socket", args.socket, channel, str(args.seconds), str(capture)]
            try:
                result = subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
                                        text=True, timeout=args.timeout, check=False)
            except subprocess.TimeoutExpired:
                print(f"NO\t{channel}\ttimeout", file=sys.stderr)
                continue
            match = PAT_RE.search(result.stderr)
            size = capture.stat().st_size if capture.exists() else 0
            if result.returncode == 0 and match and size:
                programs = match.group(1)
                detected.append((channel, size, programs))
                print(f"OK\t{channel}\t{size}\t{programs}", file=sys.stderr)
            else:
                print(f"NO\t{channel}\texit={result.returncode}", file=sys.stderr)

    print("# Generated by asie5607-probe-u3-satellite; merge into channels.yml.")
    print("# Mirakurun will discover services and gather EPG after restart.")
    for channel, _size, _programs in detected:
        channel_type, name = mirakurun_item(channel)
        print(f"- name: {name}")
        print(f"  type: {channel_type}")
        print(f"  channel: {channel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
